/*
 * This file is generated by jOOQ.
*/
package database.tables;


import database.Public;
import database.tables.records.CodersRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Coders extends TableImpl<CodersRecord> {

    private static final long serialVersionUID = -262942147;

    /**
     * The reference instance of <code>public.coders</code>
     */
    public static final Coders CODERS = new Coders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodersRecord> getRecordType() {
        return CodersRecord.class;
    }

    /**
     * The column <code>public.coders.name</code>.
     */
    public final TableField<CodersRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>public.coders.age</code>.
     */
    public final TableField<CodersRecord, Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.coders</code> table reference
     */
    public Coders() {
        this("coders", null);
    }

    /**
     * Create an aliased <code>public.coders</code> table reference
     */
    public Coders(String alias) {
        this(alias, CODERS);
    }

    private Coders(String alias, Table<CodersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Coders(String alias, Table<CodersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Coders as(String alias) {
        return new Coders(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Coders rename(String name) {
        return new Coders(name, null);
    }
}
