/*
 * This file is generated by jOOQ.
*/
package database;


import database.tables.Coders;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.coders</code>.
     */
    public static final Coders CODERS = database.tables.Coders.CODERS;
}
